### ISSUE TITLE
Getting TypeError: set is not iterable when updating documents

### ISSUE THREAD

**Issue by davideshay** [Terreii/use-pouchdb#91]
[note]: # ' ^^ Provide a general summary of the issue in the title above. ^^ '

## Description

[note]: # " Describe the problem you're encountering. "
I have a react page connecting with a "useDoc" hook getting a single document.  It brings this document up for editing, and then after updates are made and the user clicks on a button to update, I get an error like this:
```TypeError: set is not iterable
    at notify (subscription.js:171:1)
    at subscription.js:157:1
```

The useDoc hook has no parameters other than the document ID.
Updates to the document are done with a generic document update hook based on the example documentation on the web page.

Here is the code for the update command:

```export function useUpdateGenericDocument() {
  const db = usePouch();
  return useCallback(
    async (updatedDoc: any) => {
          let curDateStr=(new Date()).toISOString()
          updatedDoc.updatedAt = curDateStr;
          let response: PouchResponse = cloneDeep(PouchResponseInit);
          try { response.pouchData = await db.put(updatedDoc); }
          catch(err) { response.successful = false; response.fullError = err;}
          if (!response.pouchData.ok) { response.successful = false;}
      return response
    },[db])
}
```

This update hook works fine and throws no errors unless called by a page with useDoc().

If I change the useDoc() hook to just code using db.get, I don't get an error either, but I'm also not subscribed to updates and won't see them if the page changes. Was hoping to keep that functionality because this is for a distributed app where other users could make changes on their own copies which replicate back to this one, and I'd rather have the screen refresh with those updates when they happen.

Also, although I get this error message, the data does seem to update properly and flow upstream to replicas as well.

[tip]: # ' Do NOT give us access or passwords to your actual CouchDB or PouchDB! '

## Steps to Reproduce

[note]: # ' Include commands to reproduce, if possible. curl is preferred. '

My app has a lot more code, but I believe it can be reproduced by:

- Creating a React component that uses useDoc() hook
- Display data on page
- Have button to update. When update, either use db.put directly or through custom hook

## Expected Behavior

No error

[note]: # ' Tell us what you expected to happen. '

## Your Environment

[tip]: # ' Include as many relevant details about your environment as possible. '
[tip]: # ' You can paste the output of curl http://YOUR-COUCHDB:5984/ here. '

- CouchDB version used: 3.2.2
- PouchDB version used:  7.3.1
- React version used: 18.2
- Browser name and version: Chrome,  Safari
- Operating system and version: Mac OS

**Comment by davideshay** [comment]
Just as an FYI, I wrote my own very lightweight version of useDoc that still monitors changes and does not produce the error above.  Not sure if this would help in debugging or if anyone else happens to have this same problem, this is at least a workaround:

```
export function useGetOneDoc(docID: string) {
  const db = usePouch();
  const changesRef = useRef<any>();
  const [doc,setDoc] = useState<any>(null);
  const loadingRef = useRef(true);

  async function getDoc(id: string) {
      loadingRef.current = true;
      changesRef.current = db.changes({since: 'now', live: true, include_docs: true, doc_ids: [id]})
      .on('change', function(change) { console.log("changed",cloneDeep(change)); setDoc(change.doc); })
      let success=true; 
      let docRet = null;
      try  {docRet = await db.get(id);}
      catch(err) {success=false;}
      loadingRef.current = false;
      if (success) {setDoc(docRet)};
    }
    
  useEffect( () => {
      getDoc(docID)
      return ( () => { if (changesRef.current) {changesRef.current.cancel()};})  
  },[])  

  return {loading: loadingRef.current, doc};
}
```

Functional, but still could use improvement for sure.
